### ISSUE TITLE
Tuff bricks have no overlay

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#10]
Resource pack Version: Version: Alpha1.0.1a
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/6b3c534a-43b4-438c-b6b2-523a687c9ba2)

**Comment by devoneox** [comment]
I haven't made the tuff bricks overlays yet. This will be fixed later.

**Comment by devoneox** [comment]
By the way I'll maybe add support for 1.21 blocks in the next update.
