### ISSUE TITLE
Wood Planks and Stone have weird overlay issue

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#11]
Resource pack Version: Version: Alpha1.0.2a experimental 
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

When two of the same type of wood planks are on two sides of a stone block, the stone only shows the left planks overlay and not the right. See various test cases below. 

![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/37cddfb9-4a18-4e0c-95f4-0be78d0508c7)
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/bcb429db-5b80-4b4a-9c71-916824891249)

However, if the same type plank is above the stone, it will show the wood texture.  
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/111583b0-079f-40e2-9c59-9fc438bcb7d5)

But not if it is any other block, like a different plank type
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/50630e78-7ef9-427a-86f5-ee62985afe9d)

Also, if the wood textures are not the same wood species, the right overlay will show.
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/62dbf90a-5cc5-46ef-ab66-67bd206c766e)

This seems to be a very nuanced edge case issue.

**Comment by devoneox** [comment]
This is because the actual 5.png file misses a part. This fix is easy since I just have to replace the actual file with a copy of 8.png.
