### ISSUE TITLE
Deepslate Tiles have some interesting overlay issues

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#13]
Resource pack Version: Version: Alpha1.0.2a Experimental 
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

It seems that for deepslate tiles, overlay 12.png is used when it should be using 10.png  See pattern used with (currently broken)  cracked stone bricks on stone. Also affects other blocks like netherbrick, red netherbrick, brick, mud brick, and all logs/stripped logs

![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/fdcff972-24ca-4e04-8c59-e3a216be57bd)

**Comment by EXOgreen** [comment]
It also seems to be using 10.png when it should be using 12.png (or 11, they look identical)
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/8c2f1430-c5dc-4647-aa66-107ef97afbd7)

**Comment by devoneox** [comment]
I just messed up the order when I was batch renaming the files. I re-ordered it and ow it looks fine ! IThis fix will be available later.
