### ISSUE TITLE
Blocks missing Mud Bricks overlay

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#16]
Resource pack Version: Version: Alpha1.0.2a Experimental 
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

The Mud Brick Overlay is missing from at least

Stone, all wood logs, all stripped wood logs

![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/bb6d173f-8835-431d-8fee-598ad106cbeb)
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/da5fd76a-3b05-411e-8a5a-a2f6e9e01c3e)

**Comment by devoneox** [comment]
Actually, mud bricks don't have any overlay. I'll add this feature in the next update.
