### ISSUE TITLE
Warped Planks wood connection issue

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#2]
Resource pack Version: Version: Alpha1.0.1a
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

While testing the connection options of your pack I found that the Warped Planks do not overlap the plank to their right. 
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/67bfa0f3-7e91-49ca-a822-70e535a91970)
This applies to all directions the block can be placed
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/7c561850-e71d-46f7-94ac-7af771b04353)

I briefly looked at the files, but I am not sure if it's an issue that the warped planks don't add an overlay to their right-side neighbors, or whether the right-side neighbors doesn't match the warped planks.

I will continue testing. Thanks for making this pack!

**Comment by devoneox** [comment]
Thanks, I briefly looked at the warped_planks.properties files and I forgot the "method=overlay" argument. I fixed it and the update will be available soon.
