### ISSUE TITLE
Path blocks tops displaying overlays

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#22]
Resource pack Version: Version: V1.1 - 1.20-1.20.4
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

![2024-03-23_19 17 03](https://github.com/devoneox/deep-origins-overlays/assets/7752505/454cf9ce-bbe2-4ef0-9747-e7069e076a13)

**Comment by devoneox** [comment]
I know this issue, but I don't really know how to fix it. I can just completely remove dirt overlays on dirt path (only top side) but there has to be a better option.
