### ISSUE TITLE
Grass-like block-below issues

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#3]
Resource pack Version: Version: Alpha1.0.1a
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

Podzol and Nylium grasses overlay the grass texture to the block below, Meanwhile, Mycelium doesnt overlay anything to the block below 
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/1f3e959f-220d-441f-bd4f-8eecf824ef13)
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/1bbe212d-f573-4730-8cb2-ce6897e486a4)

*note, all only tested with stone

**Comment by devoneox** [comment]
I look in the texture pack's files, and I forgot to set the tiles to 20-36 instead of 0-16 in the game's files. This is easily fixable.
