### ISSUE TITLE
Not Working at all

### ISSUE THREAD

**Issue by Yeuogu** [devoneox/deep-origins-overlays#30]
version: 1.20.6

https://github.com/devoneox/deep-origins-overlays/assets/170952704/4d3bcb19-08dc-4234-98da-72c91528898a

I have continuity mod installed and the texture pack is not working as intended

**Comment by devoneox** [comment]
This bug came from the .zip file being corrupted and the files just missing. You can just download it from GitHub waiting for me to replace the corrupted archives with the new ones.
