### ISSUE TITLE
Overlays on dirt / podzol & sand / wood textures. 

### ISSUE THREAD

**Issue by Dantich-sfg** [devoneox/deep-origins-overlays#33]
![image](https://github.com/user-attachments/assets/2fb4b6c9-7e9c-4572-9dfa-a09f170eaeb7)
![image](https://github.com/user-attachments/assets/30828ab5-f4a6-4bdb-bcb9-d0d6884f56bf)

Reported this to the continuity mod as well, but it seems like its DOO's issue. Am not sure what causes it, but one of other RPs that I use (stay true) also causes this. 

What I've done for testing - disabled DOO and Stay True - the issue is fixed. 
Removed DOO, kept ST - the issue stayed, removed ST and kept DOO - the issue stayed.

**Comment by airon-main** [comment]
![2024-10-20_05 21 56_4K](https://github.com/user-attachments/assets/58865c18-f7d8-43ed-a97b-2654ecdd8b84)
same as moss with sands
DOO: v1.2.2

**Comment by devoneox** [comment]
I will be looking for the cause of this issue. Thank you for reporting it.

**Comment by devoneox** [comment]
I have no idea where the dirt/podzol texture issue does come from, it works totally fine for me. The sand/wood and sand/moss issues come from my resource pack and I am currently fixing them.

**Comment by Dantich-sfg** [comment]
I know it's late as hell, but I've figured out what was causing dirt/podzol & dirt/gravel bug. 
It was a resource pack Simple Grass Flowers. 
I'll do run down just in case anyone has this issue - if Stay True, DOO and Simple Grass Flowers are present, you need to have ST and DOO to override SGF. It makes sense since SGF has it's own grass texture and breaks it all.
