### ISSUE TITLE
Issues with Concrete

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#4]
Resource pack Version: Version: Alpha1.0.1a
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

Black concrete is not being overlaid by a few textures. Namely, grass, podzol, mycelium, dirt, rooted dirt, and gravel.
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/4ee9b6f7-3b99-443b-b2e8-4f84e9480de0)

However, there seems to be more interesting things going on when I searched through the files. All concrete powders include their own color concrete (not sure what this accomplishes) but a few concretes are included in other files, listed below. Hopefully this helps.

 Cyan Concrete is included in
	dirt (dirt.properties)
	rooted dirt (rooted_dirt.properties)
	Podzol (0 and 20)
	grass_block (0, 20, 40)
	mycelium (0 and 20)
	gravel (gravel.properties)

Black Concrete is included in
	Skulk (skulk.properties)
	coarse_dirt (coarse_dirt.properties)
	snow_block (0 and 20)
	Sand (0.properties)
	red_sand (0.properties)
	crimson_nylium (0.properties)
	warped_nylium (0.properties)
	moss_block (moss_block.properties)
	
Blue Concrete and Brown Concrete is included in
	Skulk (skulk.properties)
	dirt (dirt.properties)
	rooted dirt (rooted_dirt.properties)
	coarse_dirt (coarse_dirt.properties)
	podzol (0 and 20)
	grass_block (0, 20, 40)
	mycelium (0 and 20)
	snow_block (0 and 20)
	Sand (0.properties)
	red_sand (0.properties)
	crimson_nylium (0.properties)
	warped_nylium (0.properties)
	moss_block (moss_block.properties
	gravel (gravel.properties)

**Comment by EXOgreen** [comment]
I didn't explicitly say this, but I thought I'd be thorough. I was having no overlay issue with any other colors of concrete.

**Comment by devoneox** [comment]
This would be later fixed, maybe in the 1.0.3 update...

**Comment by devoneox** [comment]
I had the same issue with black terracotta and glazed terracotta... I'm fixing all of those issues for the next update.

**Comment by devoneox** [comment]
I just forgot a part of the code in the grass block, podzol, mycelium, dirt, rooted dirt and gravel, this issue was just part of a much bigger issue. Thanks for reporting it !
