### ISSUE TITLE
Skulk Issues

### ISSUE THREAD

**Issue by EXOgreen** [devoneox/deep-origins-overlays#6]
Resource pack Version: Version: Alpha1.0.1a
MC Version:1.20.4
Mods: Fabric API 0.96.4+1.20.4 and Continuity 3.0.0-beta4+1.20.2

There are 3 issues with the Skulk overlay

1. Image 0 has the third frame misaligned by one pixel up. Created pull request.
2. Image 16 gains a pixel for the third and fourth frames. I didn't fix this as I don't know if you want to keep or remove the pixel.
3. When 3 skulk align north, west, and east of a block, no overlay image is shown.
![image](https://github.com/devoneox/deep-origins-overlays/assets/7752505/3a9af9d0-2ba2-4eaa-a391-062b0935cd5c)

**Comment by devoneox** [comment]
Thanks, I was already working on fixing those issues in the next (small) update.
